### ISSUE TITLE
transactor - user 

### ISSUE THREAD

**Issue by learner4** [IBM-Blockchain/learn-chaincode#11]
Is there a way for me to create users (end-user who would also be the transactor/solution-user). apart from the list of users that are available from the bluemix "Network's Enrolled IDs" then going through registrar REST call?
I mean - I would like to create Network Enrolled IDs myself, then call registrar service to register those users and transact with these custom users I create on network and register them to be used on chaincode transaction?
Would appreciate documentation and sample on how this would work.

**Comment by masterDev1985** [comment]
Yes, there is!  The CA is the peer that manages the identities on the network, and it has an interface that allows you to create new users on the network.  The version of the Hyperledger fabric that is used in the Bluemix service exposes this interface through grpc.  The commercial paper demo uses a connector to access this interface and register new users.  The code linked below is the module that allows it do this.  Of course, you're welcome to use it too!

https://github.com/IBM-Blockchain/cp-web/tree/master/utils/loopback-connector-obcca

The unit tests under the test folder are great examples for how to use the module, but I'll highlight the main one from [here](https://github.com/IBM-Blockchain/cp-web/blob/master/utils/loopback-connector-obcca/test/unit/02-test-connector.js#L46):
```
var testUser = {
    identity: "testUser" + Date.now(),
    role: 1,
    account: "bank_a",
    affiliation: "00001"
};

var registeredUser;

test('Register User', function (t) {
    t.plan(1);

    dataSource.connector.registerUser(testUser, function (err, response) {

        if (err) {
            t.fail('registerUser failed: ' + err);
        }
        else {
            registeredUser = response;
            t.pass('should return token');
        }

    });

});
```

After registering the user against the CA, you need to log that user in against your peers using the registrar endpoint of the rest interface, just as you do with the users that were created by the service.

FYI, the fabric developers are working on a newer version of the SDK that simplifies the creation of new users.  See below for some documentation on how to use it:
https://github.com/hyperledger/fabric/tree/master/sdk/node

**Comment by dhyey20** [comment]
Closed due to inactivity.
