### ISSUE TITLE
Bluemix Blockchain Monitor error

### ISSUE THREAD

**Issue by amitoj** [IBM-Blockchain/learn-chaincode#13]
Hi,

Trying to create a blockchain service on Bluemix to run my learn-chaincode go app but keep getting following error message

> 
Whoops
The information you sent to access your instance of Blockchain was incorrectly formatted.
> 

I can see that the blockchain service is available in the dashboard but there is no UI (monitor page) to configure the service as described in the learn-chaincode tutorial.

**Comment by dshuffma-ibm** [comment]
There are some known session related issues when using the safari browser.  We have also seen issues if you are logging in and out of multiple Bluemix accounts. In any case try chrome or firefox in incognito/private mode.

**Comment by amitoj** [comment]
Yes, i was using Safari from my Macbook.
It works fine from Chrome.

Thanks.
