### ISSUE TITLE
Registrar - rpc error

### ISSUE THREAD

**Issue by Nosykaa** [IBM-Blockchain/learn-chaincode#18]
Hi, 

I'm currently doing the tutorial. But when I try to do the registrar step, I always have the same error : 
{
  "Error": "rpc error: code = 2 desc = 'grpc: the client connection is closing'"
}
I'm testing on bluemix.

Do you know why I have this error ? What am I doing wrong ?

Thanks
Nosykaa

**Comment by dshuffma-ibm** [comment]
So you are doing [this tutorial](https://github.com/IBM-Blockchain/learn-chaincode/blob/master/README.md)? Is the error response you posted coming from the HTTP request (the swagger page)? Where exactly are you seeing this error?

Correct enrollment (aka the registrar step) is to send a HTTP POST to `https://<your peer name>:<your peer's port>/registrar`. Body is:

```json
{ 
"enrollId": "user_type_1_xxxx",
"enrollsecret": "xxxxx"
}
```

If your request looks similar to above, then maybe you got unlucky. Delete this network and get another one to try again.

**Comment by Nosykaa** [comment]
Yes I am doing this tutorial. 
I tried to call the API from the bluemix page.
And yes, I use this format of request. 

But with the other network it is working.
Thanks
