### ISSUE TITLE
Problem building chaincode

### ISSUE THREAD

**Issue by abrinckm** [IBM-Blockchain/learn-chaincode#186]
This seems related to #42 and #35 but with a slightly different error message, this time it complains about the return type. It wants peer.Response but is instead trying to return ([]byte, error)...

```
	*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
		have Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
		want Init(shim.ChaincodeStubInterface) peer.Response
```

**Comment by dshuffma-ibm** [comment]
learn-chaincode is not hyperledger fabric v1 compatible, though its not too hard to convert it.

you can look at marbles chaincode to see the new v1 stuff. 
[new interface](https://github.com/IBM-Blockchain/marbles/blob/v3.0/chaincode/src/marbles/read_ledger.go#L43)
[return example](https://github.com/IBM-Blockchain/marbles/blob/v3.0/chaincode/src/marbles/read_ledger.go#L66)

**Comment by abrinckm** [comment]
ah okay. My fault. I was working from hyperledger-archive. Switched to using v0.6 from http://gerrit.hyperledger.org/r/fabric and it builds okay with no errors.
