### ISSUE TITLE
Can't build code due to Chaincode interface change

### ISSUE THREAD

**Issue by sstone1** [IBM-Blockchain/learn-chaincode#19]
I see the following compile errors after cloning the repository:
# github.com/sstone1/learn-chaincode/start

./chaincode_start.go:34: cannot use new(SimpleChaincode) (type _SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
    *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
        have Init(_shim.ChaincodeStub, string, []string) ([]byte, error)
        want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)
# github.com/sstone1/learn-chaincode/finished

./chaincode_finished.go:31: cannot use new(SimpleChaincode) (type _SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
    *SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
        have Init(_shim.ChaincodeStub, string, []string) ([]byte, error)
        want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)

Looks like the Chaincode interface was changed recently:

https://github.com/hyperledger/fabric/commit/23afd05632b4ab62f364ec0c3a6468050407fae4#diff-838beed13b889e014387d59c649c90f1

**Comment by youngsoldier** [comment]
Met same error on Centos( Linux).
Give up and turn to try the Marbles Demo directly.. ;)

**Comment by trevorhiley** [comment]
Same error on OSX

**Comment by csupp** [comment]
OSX appear same error.

**Comment by l2fprod** [comment]
Looks like we logged a duplicate in #22

**Comment by l2fprod** [comment]
@csupp @trevorhiley @youngsoldier @sstone1 the issue 29 I referenced above has a workaround using another branch of the hyperledger code.

**Comment by dshuffma-ibm** [comment]
also see https://github.com/IBM-Blockchain/learn-chaincode/pull/20

**Comment by mzobe** [comment]
Facing same error with FreeBSD 11 with go v 1.7 it working fine before the upgrade.

**Comment by mzobe** [comment]
Same issue with lubuntu:

./chaincode_start.go:34: cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
	*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
		have Init(*shim.ChaincodeStub, string, []string) ([]byte, error)
		want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)

**Comment by masterDev1985** [comment]
https://github.com/IBM-Blockchain/learn-chaincode#versions-and-supported-platforms

We've added some documentation for using this demo on both the v0.5 and the v0.6 releases of the fabric.  For instructions on how to acquire a specific release of the fabric, following the link below:

https://github.com/IBM-Blockchain/learn-chaincode/blob/master/docs/setup.md#hyperledger-fabric

**Comment by EasonWang01** [comment]
So how to solve this?

**Comment by masterDev1985** [comment]
@EasonWang01 the fix is to download fabric v0.6 and only use that release when using the learn-chaincode tutorial.  See the documentation I linked to in my previous comment.
