### ISSUE TITLE
chaincode_start.go doesnt compile if I follow the instructions

### ISSUE THREAD

**Issue by bravera** [IBM-Blockchain/learn-chaincode#27]
Weird one this.
In the 'read' function a variable called 'valAsbytes' is used.
If I try and write this code as directed and compile I get an error because 'valAsbytes' isnt defined anywhere. Adding 'var valAsbytes []byte' solves this problem.
However, if I look at chaincode_finished.go, where the code also does not define 'valAsbytes', this seems to compile just fine.
Any ideas what I am doing wrong? Or, should this be something that is corrected?

**Comment by mrshah-at-ibm** [comment]
In the 'read' function valAsbytes is declared using the short variable declaration format `:=`

Ref: https://golang.org/ref/spec#Short_variable_declarations

Hope this helps

**Comment by bravera** [comment]
Ah - thanks very much.....I had missed that!
