### ISSUE TITLE
Create branch / tag structure to support multiple versions of fabric interfaces

### ISSUE THREAD

**Issue by mastersingh24** [IBM-Blockchain/learn-chaincode#30]
There are 2 versions of the fabric code out in the wild today.  Within the IBM BMX services, we use fabric v0.5-developer-preview and then there is the version that's in the public fabric repo.  The chaincode interface has changed between them but do to the way Golang works, there's no way for us to pull in the right version of the package without doing a few tricks.

The plan here is going to be to create / document various branches / tags in this repo to deal with that

**Comment by masterDev1985** [comment]
@mastersingh24 See the updates to this repository.  I've created branches for each release of the fabric and have documented them at the start of the tutorial.  I've also added instructions for setting up your dev environment to support each release.

**Comment by masterDev1985** [comment]
I should have closed this already.
