### ISSUE TITLE
No GO GET source files 

### ISSUE THREAD

**Issue by cesarfong** [IBM-Blockchain/learn-chaincode#31]
i am running a windows 7 machine and when i run this 

go get github.com/hyperledger/fabric/core/chaincode/shim

Nothing happens.

César

**Comment by masterDev1985** [comment]
The code was probably downloaded to your GOPATH directory.  The Golang CLI generally spits out an error if there was a problem.
https://golang.org/doc/code.html#GOPATH

Run `cd $GOPATH/src`.  You should see a directory called `hyperledger` there.  Follow the directories down to the shim folder.  Let us know what you find.

**Comment by cesarfong** [comment]
It seems to be working now. thanks but i guess i need only to wait some minutes to complete.. :)

**Comment by masterDev1985** [comment]
No worries!
