### ISSUE TITLE
GetState with wildcard

### ISSUE THREAD

**Issue by fu-nakayama** [IBM-Blockchain/learn-chaincode#32]
I have a simple question.
Can I GetState with specifying wildcard?
I'd like to get multiple or all the data from KVS.

As far as I checked the documentation, GetState requires to specify one key for getting only one data associated to the key.

Regards,
Fumio Nakayama

**Comment by mastersingh24** [comment]
@fu-nakayama  - you can't use `GetState` with wildcards.  There are a few options you can try:

`RangeQueryState` - Basically if you use some type of prefix with your keys, you can do range queries on them.  These basically use lexical order for the keys

There is also a higher order table API you can use which has methods like `GetRow` and `GetRows`

**Comment by fu-nakayama** [comment]
Thanks!!
