### ISSUE TITLE
deploy chaincode failed

### ISSUE THREAD

**Issue by lightning-li** [IBM-Blockchain/learn-chaincode#33]
I try to deploy chaincode by REST api, the chaincode path is "http://github.com/lightning-li/fabric-chaincode-sample/contract_management", it failed, the error message output by VP is : 
<img width="1272" alt="qq20160927-0 2x" src="https://cloud.githubusercontent.com/assets/7557388/18866981/ddd1c53a-84d4-11e6-962a-85f78f12ed85.png">
how can i fix the problem? @dshuffma-ibm

**Comment by mastersingh24** [comment]
@lightning-li  - you'll need to "vendor" the go-logging dependency.  In simplest terms, you'll need to add a folder named "vendor" to the base of your project directory and include the source to the go-logging package (keeping the folder structure under vendor as if you were under the src folder in your GOPATH).   Here's a nice explanation for reference:   https://blog.gopheracademy.com/advent-2015/vendor-folder/

**Comment by lightning-li** [comment]
@mastersingh24 I use "govendor init && govendor add github.com/op/go-logging" under  "http://github.com/lightning-li/fabric-chaincode-sample/contract_management" , when I deploy it again, it failed, the error message output by VP is : 
<img width="1255" alt="qq20160927-2 2x" src="https://cloud.githubusercontent.com/assets/7557388/18870239/576958e2-84e2-11e6-9acf-95d26acce043.png">

**Comment by lightning-li** [comment]
@mastersingh24 it solved my problem, thanks for your patience! 👍 👍
