### ISSUE TITLE
Missing docu on how to upload code

### ISSUE THREAD

**Issue by LarissaAuberger** [IBM-Blockchain/learn-chaincode#36]
I am pretty new to github/git and when following the instructions under
https://github.com/IBM-Blockchain/learn-chaincode
I was lost at "Deploying the chaincode".

The chapter says "In order to deploy chaincode through the rest interface, you will need to have the chaincode stored in a public git repository.", but it does not explain how to do this.

Is it sufficient to just upload the chaincode_finished.go to the repository using the  browser interface of the repository? If so, how would I create finished and start folders? If not - would it be possible to add a section on how to store the chaincode in a public repository. Thank you!

**Comment by g8rengr** [comment]
@LarissaAuberger If I understand correctly you are on Step 3 of the "Implementing your first chaincode" i.e 3. The IBM Bluemix IBM Blockchain service currently requires that chaincode to be in a GitHub repository. Therefore, if you don't already have a GitHub account, you should get one. 

If you are new to Git, first create a free account (you can click the "get one" at the end of Step 3,  text for link to getting an account. 
Then click the "do that" text in step 4. that will explain some basics of Git and there is a built in tutorial which may help as well. 

After that..the deploy steps are covered in the next section...By "forking" the repository "learn-chaincode", that is what creates the folders and code for you to use on your own machine, you do not have to copy anything manually.

I hope that helps.

**Comment by LarissaAuberger** [comment]
@g8rengr, thank your for responding to my question. I am at step "Deploying the chaincode".
I have the chaincode locally and my understanding now is I should deploy it to my own public repository. I already created a public repository, but I stuck on how to deploy my local files to that repository (including folders). Thank you!

**Comment by LarissaAuberger** [comment]
I finally understood how it works. Thanks for your help.

**Comment by masterDev1985** [comment]
@LarissaAuberger glad to hear it!  Thanks for the help, @g8rengr
