### ISSUE TITLE
Failed to query chaincode

### ISSUE THREAD

**Issue by LarissaAuberger** [IBM-Blockchain/learn-chaincode#37]
I try to query chaincode following the instructions in the documentation. 
The query failed with the following error message:

"Error when querying chaincode: Error:Failed to launch chaincode spec(premature execution - chaincode (42c213a8f0db2dfbcc1d9844eb108ab0ec1d18f1ff94d63791ac85ca08b68316e4670d09ff134e629ac0d5055ed858f9c408545b636732ec6f1eda4b8c7f638f) is being launched)"

Any help is highly appreciated. Thank you!

**Comment by dshuffma-ibm** [comment]
it might be as simple as waiting longer. if you are using a bluemix network then you will have to wait around 20 minutes for a deploy to complete. 

we are having rather server congestion and we are working towards a new backend architecture that will greatly speed up deployments.  until then though, you do have to wait a very long time before the deploy is finished.

if you have waited and still get this message, then try finding your peer's logs from the bluemix dashboard.  from bluemix click your tile to get into the service's dashboard, then click the logs tab and then click the peer that you are deploying to. when you deploy refresh these logs and look for errors or anything other clues..

**Comment by masterDev1985** [comment]
The 20 minute deploy times that @dshuffma-ibm referenced have been alleviated in the last rollout of the service.  @LarissaAuberger try to run the demo again and let us know if you have any issues.
