### ISSUE TITLE
InvokeSpec Response Body

### ISSUE THREAD

**Issue by gregmisiorek** [IBM-Blockchain/learn-chaincode#4]
hello there,

instead of "go away" message i keep getting 'random' strings when i keep clicking on "Try It Out" button: eg
{
  "jsonrpc": "2.0",
  "result": {
    "status": "OK",
    "message": "not a go away message but 'random' string here"
  },
  "id": 3
}

thx,

greg

**Comment by dshuffma-ibm** [comment]
interesting, could you post your network ID (top right in dashboard) and the body of the invoke you are sending.

**Comment by gregmisiorek** [comment]
i'm @cc9750ce-9a7f-4991-8b4b-e0a03e8e6488 and here's input:

{
    "jsonrpc": "2.0",
    "method": "invoke",
    "params": {
        "type": 1,
        "chaincodeID": {
            "name": "hashfromDeploySpecStep"
        },
        "ctorMsg": {
            "function": "write",
            "args": [
                "hello_world",
                "go away"
            ]
        },
        "secureContext": "user_type1_1st_enrollid"
    },
    "id": 3
}

**Comment by dshuffma-ibm** [comment]
Your input looks good.  Were you able to get it to work eventually?  

- Make sure there is no extra text in the wrong other input boxes.  When doing an invoke the other two fields should be blank: 
- Also make sure the json is in the correct box

Example:
![image](https://cloud.githubusercontent.com/assets/16085295/15514531/7cc4330c-21b7-11e6-8f9d-2578894cda33.png)
