### ISSUE TITLE
Deploy chaincode 

### ISSUE THREAD

**Issue by aymanx1** [IBM-Blockchain/learn-chaincode#77]
I was wondering is it possible to deploy my own chaincode on the bluemix trial account. I noticed that only 3 proposed samples are allowed.  if it is not allowed to run my chaincode is there any solution to try it online?

**Comment by MrBuggySan** [comment]
Yes you can deploy your chaincode through the REST APIs or the HFC SDK. 
Refer to this tutorial for more info: https://console.ng.bluemix.net/docs/services/blockchain/etn_sdk.html

**Comment by masterDev1985** [comment]
Thanks, @MrBuggySan
