### ISSUE TITLE
No buildable Go source files when following the instructions 

### ISSUE THREAD

**Issue by jtytan** [IBM-Blockchain/learn-chaincode#81]
I'm trying to follow the Dev setup instructions, and I'm getting an error of 

```
trojanchicken:fabric xxx$ go build .
can't load package: package .: no buildable Go source files in /Users/xxx/Documents/goProjects/hyperledger/fabric
```

There seems to be some mismatch in the instructions as well - or a lack of understanding from my part - as on one hand, the instructions first say

> You will need to make sure that the fabric release you choose is stored under `$GOPATH/hyperledger/fabric`.

But then after that, the instructions are to clone the fork into the `$GOPATH/github.com/hyperledger` path.

At this point in time, I've tried to have the `hyperledger/fabric` code in the `$GOPATH/hyperledger`, `$GOPATH/src/github.com/hyperledger`, `$GOPATH/github.com/hyperledger` locations - and I can see that I do have a `$GOPATH` set, and I always get the same error that 

> there are no buildable Go source files

 in the folders that I am attempting to run this from...

Is there a missing file from the v0.6 fork?

I used this URL: `git clone -b v0.6 http://gerrit.hyperledger.org/r/fabric`

**Comment by mrshah-at-ibm** [comment]
Are these instructions on https://github.com/IBM-Blockchain/learn-chaincode repository?

**Comment by forgeRW** [comment]
I stumbled upon this issue while searching for additional resources. Both the links [https://console.ng.bluemix.net/docs/services/blockchain/ibmblockchain_tutorials.html](url) and [https://github.com/IBM-Blockchain/learn-chaincode/blob/master/docs/setup.md](url) suggest cloning from http://gerrit.hyperledger.org/r/fabric, which is different from the one referenced by @mrshah-at-ibm [https://github.com/IBM-Blockchain/learn-chaincode ](url).

would anyone know which of the 3 links above contains the latest instructions?

**Comment by forgeRW** [comment]
> But then after that, the instructions are to clone the fork into the $GOPATH/github.com/hyperledger path.

I believe that's a typo because the snippet below it used `$GOPATH/src/github.com/hyperledger`
I didn't have an issue when I followed the snippet. Perhaps try using this `$GOPATH/src/github.com/hyperledger` again.

**Comment by sativ01** [comment]
Hi,
I have the same problem. Running on Win7
could someone please tell us what is the name of  build file that go is looking for?
I was able to `go build ./` the _chaincode_start.go_, so I know that GO works.
Thanks

**Comment by kunalbansal92** [comment]
I have same problem running on ubuntu64 bit go version go1.6.2 linux/amd64

**Comment by mrshah-at-ibm** [comment]
@sativ01 @kunalbansal92, were you able to fix the problem using @forgeRW's solution?

**Comment by binalbhavsar1** [comment]
same problem

**Comment by binalbhavsar1** [comment]
@mrshah-at-ibm  tried as per @forgeRW  solution as well.. nothing work.. can someone help

**Comment by prakashvgr** [comment]
@binalbhavsar1  even i have faced this issue, but now resolved. Here you go,

I'm using Win - 7 environment
I had referenced the below URL to clone the hyperledger repository

URL: https://console.ng.bluemix.net/docs/services/blockchain/ibmblockchain_tutorials.html

Step1: mkdir -p $GOPATH/src/github.com/hyperledger
Step2: cd $GOAPTH/src/github.com/hyperledger
Step3: git clone -b v0.6 http://gerrit.hyperledger.org/r/fabric

Then I had reference the below URL to fork and clone the IBM Blockchain - Learn chaincode repository

URL: https://github.com/IBM-Blockchain/learn-chaincode

Step4: cd $GOPATH
Step5: mkdir -p src/github.com/<YOUR_GITHUB_ID_HERE>/
Step6: cd src/github.com/<YOUR_GITHUB_ID_HERE>/
Step7: git clone -b v2.0 https://github.com/<YOUR_GITHUB_ID_HERE>/learn-chaincode.git

Step8: Two different versions of the chaincode used in this tutorial(repo): 
	Start - the skeleton chaincode from which you will start developing
	Finished - the finished chaincode

Step9: cd $GOPATH/src/github.com/<YOUR_GITHUB_ID_HERE>/learn-chaincode/start
Step10: go build ./

**Comment by binalbhavsar1** [comment]
@prakashvgr - thank you for the solution. so in between two URL you don't build.
I mean
After step3, I have tried step4:Go build. as per tutorial and I am getting the error.

**Comment by prakashvgr** [comment]
Hi @binalbhavsar1, nope., Since you have to build (execute) the chaincode repository after cloned in the development environment. Good!!! that my details helps you to resolve and explore the chaincode

**Comment by vikky08** [comment]
hi

**Comment by dshuffma-ibm** [comment]
seems resolved

**Comment by karikalansaitechnology** [comment]
can't load package: package github.com/mauri870/ransomware: no buildable Go source files in /root/Projects/Proj1/src/github.com/mauri870/ransomware
how to fix this error i don't know help me

**Comment by BALAMURUGANS15** [comment]
https://github.com/dustin/go-coap/tree/master/example/server
from this site i am running coap_server.go
at that time i am getting the below problem
coap_server.go:7:2: no buildable Go source files in /usr/lib/go-1.6/src/github.com/dustin/go-coap
please anyone reply for this problem as soon as possible

**Comment by mrshah-at-ibm** [comment]
@BALAMURUGANS15 this project has been archived and not active anymore.

**Comment by BALAMURUGANS15** [comment]
thank u mrshah-at-ibm
