### ISSUE TITLE
Version running on Bluemix needs to be updated ?

### ISSUE THREAD

**Issue by devlaptop** [IBM-Blockchain/learn-chaincode#95]
The instructions state that the current version of the API to be used to work with a Bluemix deployment is v0.5 but it looks like the version now available on Bluemix is 0.6.1

**Comment by masterDev1985** [comment]
https://github.com/IBM-Blockchain/learn-chaincode/commit/49a4a16eaafd2b6dcc9ea0cb5dec41a266108079 fixes this.  Thanks for the heads up!
